/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ArbiGates } from "./ArbiGates";

export { ArbiGates__factory } from "./factories/ArbiGates__factory";
